# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: swift
# cache: cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods
 - pod install --project-directory=Example
script:
 - xcodebuild -workspace Example/ARNotificationTest.xcworkspace -scheme ARNotificationTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
