# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10
# cache: cocoapods
podfile: Example/Podfile
env:
  #environment variables
  global:
    - SCHEME_IOS="ARNotificationTest"
    - IOS_SDK=iphonesimulator12.0
  matrix:
    - DESTINATION="OS=12.0,name=iPhone X" SCHEME="$SCHEME_IOS" SDK="$IOS_SDK"
before_install:
 - gem install cocoapods
 - pod install --project-directory=Example
script:
 - xcodebuild -workspace Example/ARNotificationTest.xcworkspace -scheme ARNotificationTest -destination "$DESTINATION" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
